### ISSUE TITLE
Please replace msec with ms in the output conform specifications

### ISSUE THREAD

**Issue by hboetes** [NETWAYS/check_sap#1]
Our check_sap plugin returns this performance data:

```
[CRITICAL] 2 criticals and 8 warnings | Entire_System-SEE-Application_Server-SIG-XN-SEE_SEE_00-R3Services-Dialog-ResponseTime=1537msec Entire_System-SEE-Application_Server-SIG-XN-SEE_SEE_00-R3Services-Dialog-ResponseTimeDialog=1537msec Entire_System-SEE-Application_Server-SIG-XN-SEE_SEE_00-R3Services-Dialog-ResponseTimeDialogRFC=1537msec Entire_System-SEE-Application_Server-SIG-XN-SEE_SEE_00-R3Services-Dialog-ResponseTimeHTTP=7123msec Entire_System-SEE-Application_Server-SIG-XN-SEE_SEE_00-R3Services-Dialog-FrontendResponseTime=1956msec Entire_System-SEE-Application_Server-SIG-XN-SEE_SEE_00-R3Services-Dialog-ResponseTime(StandardTran.)=56msec Entire_System-SEE-Application_Server-SIG-XN-SEE_SEE_00-R3Services-Update-PerformanceU1-ResponseTime=1378msec Entire_System-SEE-Application_Server-SIG-XN-SEE_SEE_00-R3Services-Update-PerformanceU2-ResponseTime=21msec Entire_System-SEE-R-3_Services-Dialog-Dialog-ResponseTime=1537msec Entire_System-SEE-R-3_Services-Dialog-Dialog-ResponseTimeDialog=1537msec Entire_System-SEE-R-3_Services-Dialog-Dialog-ResponseTimeDialogRFC=1537msec Entire_System-SEE-R-3_Services-Dialog-Dialog-ResponseTimeHTTP=7123msec Entire_System-SEE-R-3_Services-Dialog-Dialog-FrontendResponseTime=1956msec Entire_System-SEE-R-3_Services-Dialog-Dialog-ResponseTime(StandardTran.)=56msec
```

After some puzzling I discovered that icinga2 doesn't like msec, but wants the unit specified as ms

See also: https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

So as a quick fix I created this script:

```
# cat /usr/lib/nagios/plugins/check_sap
#! /bin/sh
/usr/lib/nagios/plugins/check_sap.real "$@" | sed -e 's|msec|ms|g'
```

So my kind request is to s&r msec to ms in the output.

**Comment by bunghi** [comment]
+1

**Comment by martialblog** [comment]
@RincewindsHat I guess we could do some replacement here, right? https://github.com/NETWAYS/check_sap/blob/master/check_sap.c#L626

**Comment by RincewindsHat** [comment]
probably yes, bit risky witout a proper testcase, but best effort should be good enough.

**Comment by RincewindsHat** [comment]
should be fixed with #3  although completely untested.

**Comment by hboetes** [comment]
Do you always close issues before testing the change?

**Comment by RincewindsHat** [comment]
No, only I wasn't expecting anyone to actually keep watch of this. Therefore my thoughts were, that I can close this now instantly instead of just waiting some time for nothing to happen.

But since you are actually still here, could you tell use, if the change works for you? :-)

**Comment by martialblog** [comment]
Plus, I think the change is rather trivial. But we agree that there should be testing, and we're working on improving that

**Comment by hboetes** [comment]
I'm terribly sorry, I no longer use this product. :-}
