### ISSUE TITLE
No data from remote system

### ISSUE THREAD

**Issue by picoroma** [NETWAYS/check_sap#2]
Hi!
I'm trying to use the check_sap script to retrive CCMS data.
I receive for most of the checks I tried this:
[UNKNOWN] No data available

What can be the cause of this?
Is there a way to perform a trace or something to investigate?
REgards
P.

**Comment by RincewindsHat** [comment]
Hello @picoroma
This might be a bit late, but did you solve this problem?
Or can you tell something more about it?

**Comment by picoroma** [comment]
I suppose YES..
I do not remember honestly :-) but probably we have moved to another plugin to check SAP system.
Regards
P.

**Comment by RincewindsHat** [comment]
Then I will close this issue. Sorry for the lack of response again.
